CREATE SCHEMA IF NOT EXISTS DesafioBasis DEFAULT CHARACTER SET utf8 ;
USE DesafioBasis;

CREATE TABLE IF NOT EXISTS empresa (
  cod INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(150) NOT NULL,
  cnpj VARCHAR(4) NOT NULL,
  endereco VARCHAR(150) NOT NULL,
  PRIMARY KEY (cod),
  UNIQUE INDEX cnpj (cnpj))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS funcionario (
  cod INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(150) NOT NULL,
  data_nascimento DATE NOT NULL,
  cpf VARCHAR(11) NOT NULL,
  cod_empresa INT(11) NOT NULL,
  PRIMARY KEY (cod),
  UNIQUE INDEX cpf (cpf),
  CONSTRAINT fk_empFunc
    FOREIGN KEY (cod_empresa)
    REFERENCES empresa(cod)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;
